### PR TITLE
simple typo fixes

### PR DESCRIPTION
**Pull request by Resseguie**

### CODE REVIEW

**Comment by odewahn** [comment]
Thanks for these, @Resseguie.  I'm traveling this week and have limited bandwidth, so it will take me a bit longer to merge these.  Coming soon, though...

**Comment by Resseguie** [comment]
@odewahn I merged with the latest master. (sorry about the extra couple commits, my git-fu was apparently lacking today...)

**Comment by odewahn** [comment]
Thanks,  @Resseguie, and sorry I let this languish for so long!

**Comment by Resseguie** [comment]
np, I just happened across it doing some more docker reading and figured it was easier for me to merge my own. glad to contribute.

**Pull request merged**
